KANA_TO_READING = {'あ': 'A.HIRA  ', 'い': 'I.HIRA  ', 'う': 'U.HIRA  ', 'え': 'E.HIRA  ', 'お': 'O.HIRA  ', 'か': 'KA.HIRA ', 'が': 'GA.HIRA ', 'き': 'KI.HIRA ', 'ぎ': 'GI.HIRA ', 'く': 'KU.HIRA ', 'ぐ': 'GU.HIRA ', 'け': 'KE.HIRA ', 'げ': 'GE.HIRA ', 'こ': 'KO.HIRA ', 'ご': 'GO.HIRA ', 'さ': 'SA.HIRA ', 'ざ': 'ZA.HIRA ', 'し': 'SHI.HIRA', 'じ': 'JI.HIRA ', 'す': 'SU.HIRA ', 'ず': 'ZU.HIRA ', 'せ': 'SE.HIRA ', 'ぜ': 'ZE.HIRA ', 'そ': 'SO.HIRA ', 'ぞ': 'ZO.HIRA ', 'た': 'TA.HIRA ', 'だ': 'DA.HIRA ', 'ち': 'CHI.HIRA', 'ぢ': 'JI.HIRA ', 'つ': 'TSU.HIRA', 'づ': 'ZU.HIRA ', 'て': 'TE.HIRA ', 'で': 'DE.HIRA ', 'と': 'TO.HIRA ', 'ど': 'DO.HIRA ', 'な': 'NA.HIRA ', 'に': 'NI.HIRA ', 'ぬ': 'NU.HIRA ', 'ね': 'NE.HIRA ', 'の': 'NO.HIRA ', 'は': 'HA.HIRA ', 'ば': 'BA.HIRA ', 'ぱ': 'PA.HIRA ', 'ひ': 'HI.HIRA ', 'び': 'BI.HIRA ', 'ぴ': 'PI.HIRA ', 'ふ': 'FU.HIRA ', 'ぶ': 'BU.HIRA ', 'ぷ': 'PU.HIRA ', 'へ': 'HE.HIRA ', 'べ': 'BE.HIRA ', 'ぺ': 'PE.HIRA ', 'ほ': 'HO.HIRA ', 'ぼ': 'BO.HIRA ', 'ぽ': 'PO.HIRA ', 'ま': 'MA.HIRA ', 'み': 'MI.HIRA ', 'む': 'MU.HIRA ', 'め': 'ME.HIRA ', 'も': 'MO.HIRA ', 'や': 'YA.HIRA ', 'ゆ': 'YU.HIRA ', 'よ': 'YO.HIRA ', 'ら': 'RA.HIRA ', 'り': 'RI.HIRA ', 'る': 'RU.HIRA ', 'れ': 'RE.HIRA ', 'ろ': 'RO.HIRA ', 'わ': 'WA.HIRA ', 'ん': 'N.HIRA  '}
HIRAGANA_ORDER_TO_READING = {0: b'A.HIRA  ', 1: b'I.HIRA  ', 2: b'U.HIRA  ', 3: b'E.HIRA  ', 4: b'O.HIRA  ', 5: b'KA.HIRA ', 6: b'GA.HIRA ', 7: b'KI.HIRA ', 8: b'GI.HIRA ', 9: b'KU.HIRA ', 10: b'GU.HIRA ', 11: b'KE.HIRA ', 12: b'GE.HIRA ', 13: b'KO.HIRA ', 14: b'GO.HIRA ', 15: b'SA.HIRA ', 16: b'ZA.HIRA ', 17: b'SHI.HIRA', 18: b'JI.HIRA ', 19: b'SU.HIRA ', 20: b'ZU.HIRA ', 21: b'SE.HIRA ', 22: b'ZE.HIRA ', 23: b'SO.HIRA ', 24: b'ZO.HIRA ', 25: b'TA.HIRA ', 26: b'DA.HIRA ', 27: b'CHI.HIRA', 28: b'JI.HIRA ', 29: b'TSU.HIRA', 30: b'ZU.HIRA ', 31: b'TE.HIRA ', 32: b'DE.HIRA ', 33: b'TO.HIRA ', 34: b'DO.HIRA ', 35: b'NA.HIRA ', 36: b'NI.HIRA ', 37: b'NU.HIRA ', 38: b'NE.HIRA ', 39: b'NO.HIRA ', 40: b'HA.HIRA ', 41: b'BA.HIRA ', 42: b'PA.HIRA ', 43: b'HI.HIRA ', 44: b'BI.HIRA ', 45: b'PI.HIRA ', 46: b'FU.HIRA ', 47: b'BU.HIRA ', 48: b'PU.HIRA ', 49: b'HE.HIRA ', 50: b'BE.HIRA ', 51: b'PE.HIRA ', 52: b'HO.HIRA ', 53: b'BO.HIRA ', 54: b'PO.HIRA ', 55: b'MA.HIRA ', 56: b'MI.HIRA ', 57: b'MU.HIRA ', 58: b'ME.HIRA ', 59: b'MO.HIRA ', 60: b'YA.HIRA ', 61: b'YU.HIRA ', 62: b'YO.HIRA ', 63: b'RA.HIRA ', 64: b'RI.HIRA ', 65: b'RU.HIRA ', 66: b'RE.HIRA ', 67: b'RO.HIRA ', 68: b'WA.HIRA ', 69: b'O.WO.HIR', 70: b'N.HIRA  '}
HIRAGANA_READING_TO_ORDER = {b'A.HIRA  ': 0, b'I.HIRA  ': 1, b'U.HIRA  ': 2, b'E.HIRA  ': 3, b'O.HIRA  ': 4, b'KA.HIRA ': 5, b'GA.HIRA ': 6, b'KI.HIRA ': 7, b'GI.HIRA ': 8, b'KU.HIRA ': 9, b'GU.HIRA ': 10, b'KE.HIRA ': 11, b'GE.HIRA ': 12, b'KO.HIRA ': 13, b'GO.HIRA ': 14, b'SA.HIRA ': 15, b'ZA.HIRA ': 16, b'SHI.HIRA': 17, b'JI.HIRA ': 28, b'SU.HIRA ': 19, b'ZU.HIRA ': 30, b'SE.HIRA ': 21, b'ZE.HIRA ': 22, b'SO.HIRA ': 23, b'ZO.HIRA ': 24, b'TA.HIRA ': 25, b'DA.HIRA ': 26, b'CHI.HIRA': 27, b'TSU.HIRA': 29, b'TE.HIRA ': 31, b'DE.HIRA ': 32, b'TO.HIRA ': 33, b'DO.HIRA ': 34, b'NA.HIRA ': 35, b'NI.HIRA ': 36, b'NU.HIRA ': 37, b'NE.HIRA ': 38, b'NO.HIRA ': 39, b'HA.HIRA ': 40, b'BA.HIRA ': 41, b'PA.HIRA ': 42, b'HI.HIRA ': 43, b'BI.HIRA ': 44, b'PI.HIRA ': 45, b'FU.HIRA ': 46, b'BU.HIRA ': 47, b'PU.HIRA ': 48, b'HE.HIRA ': 49, b'BE.HIRA ': 50, b'PE.HIRA ': 51, b'HO.HIRA ': 52, b'BO.HIRA ': 53, b'PO.HIRA ': 54, b'MA.HIRA ': 55, b'MI.HIRA ': 56, b'MU.HIRA ': 57, b'ME.HIRA ': 58, b'MO.HIRA ': 59, b'YA.HIRA ': 60, b'YU.HIRA ': 61, b'YO.HIRA ': 62, b'RA.HIRA ': 63, b'RI.HIRA ': 64, b'RU.HIRA ': 65, b'RE.HIRA ': 66, b'RO.HIRA ': 67, b'WA.HIRA ': 68, b'O.WO.HIR': 69, b'N.HIRA  ': 70}

def get_kana_to_reading():
    return KANA_TO_READING

def get_hiragana_order_to_reading():
    return HIRAGANA_ORDER_TO_READING

def get_hiragana_reading_to_order():
    return HIRAGANA_READING_TO_ORDER